kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # 1. Labels the node so the ingress controller knows where to schedule
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    # 2. Maps physical ports on your laptop to ports inside the Kind container
    extraPortMappings:
      - containerPort: 30000 # Maps to the Traefik web entrypoint
        hostPort: 8000
        protocol: TCP
      - containerPort: 30443 # Maps to the Traefik websecure entrypoint
        hostPort: 4430
        protocol: TCP
