deployment:
  kind: DaemonSet

ports:
  web:
    port: 30080
    hostPort: 80
  websecure:
    port: 30443
    hostPort: 443

nodeSelector:
  ingress-ready: "true"

service:
  enabled: true
  type: NodePort
  ports:
    web:
      nodePort: null
    websecure:
      nodePort: null
